# Sesi 4 : Numpy

### Nama : Ninda Nurismiranda
### Program : Introduction to Python for Data Science

#### Install and Import Numpy

In [1]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
## Adding Vector menggunakan pure python without numpy 
def pythonsum(n):
    a = b = list(range(n)) ## range returns a lazy sequence object - it does not return a list
    c = [] 
    for i in range(len(a)):
        x = a[i] ** 2 
        y = b[i] ** 3 
        c.append(x + y )
    return c 
    
c = pythonsum(10)    
print(c)

[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]


In [4]:
## Adding Vector menggunakan pure python without numpy 
def numpysum(n):
    a = np.arange(n) ** 2 
    b = np.arange(n) ** 3 
    c=a+ b
    return c

x = numpysum(10) 
print(x)

[  0   2  12  36  80 150 252 392 576 810]


In [5]:
## membandingkan kecepatan antara numpy dg List core python 
from datetime import datetime
size = 100
start = datetime.now()
c = pythonsum(size)
delta = datetime.now() - start
print("The last 2 elements of the sum", c[-2:])
print("PythonSum elapsed time in microseconds", delta.microseconds)

The last 2 elements of the sum [950796, 980100]
PythonSum elapsed time in microseconds 0


In [6]:
start = datetime.now()
c = numpysum(size)
delta = datetime.now() - start
print("The last 2 elements of the sum", c[-2:])
print("NumPySum elapsed time in microseconds", delta.microseconds)

The last 2 elements of the sum [950796 980100]
NumPySum elapsed time in microseconds 0


### Array

In [7]:
import numpy 

In [10]:
a = np.array ([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print (a[0])

[1 2 3 4]


##### Creating Array

np.array()
np.zeros()
np.ones()
np.empty()
np.arange()

In [16]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [18]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [20]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [21]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [25]:
# You can create an array with a range of elements
print(np.arange(4))
print(np.arange(0,10,2)) # start 0 , Stop = 10 , step =2 

[0 1 2 3]
[0 2 4 6 8]


Apa yang dilakukan **arange([start],stop,[step])** adalah mengatur angka dari awal hingga berhenti, dalam langkah langkah. Inilah artinya untuk np.arange(0,10,2)

In [26]:
print(np.arange(2,29,5))

[ 2  7 12 17 22 27]


#### Add, Remove and Sort

* np.append()
* np.delete()
* np.sort()

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)

[1 2 3 4 5 6 7 8]


In [28]:
arr = np.append(arr, [9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [29]:
# menghapus index 1 
np.delete(arr, 1)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Multi-dimensional Arrays

In [31]:
multi_list = [[0, 1, 2, 3], [10, 11, 12,13]]
print(type(multi_list))
multi_list

<class 'list'>


[[0, 1, 2, 3], [10, 11, 12, 13]]

In [32]:
a = np.array(multi_list)
print(type(a))
a

<class 'numpy.ndarray'>


array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

##### ndim, size, and shape

In [ ]:
ndarray.ndim #untuk mengetahui jumlah axes, atau dimensi dari array
ndarray.size #untuk mengetahui jumlah total elemen array
nd.array.shape #untuk menampilkan tupple integer yang menunjukkan jumlah elemen yang disimpan disepanjang setiap dimensi array

In [33]:
arr_1 = np.array([2, 1, 5, 3, 7, 4, 6, 8])  # 1 dimensi
print(arr_1)

[2 1 5 3 7 4 6 8]


In [34]:
arr_1.ndim # Untuk mengetahui jumlah dimensi pada data menggunakan fungsi ndim.

1

In [35]:
arr_1.shape # Array a memiliki shape ...5, yaitu panjang array pada 1-dimensi array.

(8,)

In [37]:
arr_1.size

8

In [48]:
# 3 dimensi 
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [49]:
array_example.ndim

3

In [50]:
array_example.shape 

(3, 2, 4)

In [51]:
array_example.size

24

#### Sorting Array

 np.sort?  ## Signature: np.sort(a, axis=-1, kind=None, order=None)

 ----------------------------------
|   kind    |  speed  |    stable |
|:--------|:-------|:--------| 
|'quicksort' |   1    |          no |
|'heapsort'  |   3   |          no |
|'mergesort' |   2   |       yes |
|'timsort'   |   2  |          yes |


In [39]:
data = np.array([[4, 1, 0, 5],[1, 5, 3, 4]])
data

array([[4, 1, 0, 5],
       [1, 5, 3, 4]])

In [40]:
# menambahkan parameter axis =1 
data.sort(axis=1)
print(data)

[[0 1 4 5]
 [1 3 4 5]]


In [41]:
## dengan kita menambahkan parameter "axis=0" kita menghasilkan 
## array baru yang merupakan hasil sorting berdasarkan per kolom 

In [42]:
data = np.array([[4, 1, 0, 5],[1, 5, 3, 4]])
# menambahkan parameter axis =0 
print(data)
print("sebelum di sort axis=0")
print(10*"=====")
data.sort(axis=0)
print(data)

[[4 1 0 5]
 [1 5 3 4]]
sebelum di sort axis=0
[[1 1 0 4]
 [4 5 3 5]]


In [43]:
#### sorting dengan membuat structure array
dtype = [('name', 'S10'), ('height', float), ('age', int)]  ##  name type string , heigh type float , age type int
values = [('Arthur', 1.8, 41), 
          ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype) # create a structured array
print(a)

[(b'Arthur', 1.8, 41) (b'Lancelot', 1.9, 38) (b'Galahad', 1.7, 38)]


In [44]:
x = np.sort(a, order='name')  
print(x)

[(b'Arthur', 1.8, 41) (b'Galahad', 1.7, 38) (b'Lancelot', 1.9, 38)]


In [45]:
np.sort(a, order=['age', 'height'])  

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [46]:
values[1] # menghasilkan tuple

('Lancelot', 1.9, 38)

In [47]:
values[0][0] ## arthur , 

'Arthur'

##### Reshape

In [52]:
import numpy as np

In [ ]:
np.reshape() #Memberikan bentuk baru ke array tanpa mengubah datanya

In [54]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [55]:
b = a.reshape(2,3)
print(b)


[[0 1 2]
 [3 4 5]]


In [56]:
##For example, ``a.reshape(10, 11)`` is equivalent to ``a.reshape((10, 11))``
c = a.reshape((3,2))
print(c)

[[0 1]
 [2 3]
 [4 5]]


In [57]:
a.reshape (6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

##### Convert 1D to 2D

np.newaxis
np.expand_dims
untuk meningkatkan dimensi array yang ada

In [58]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [59]:
# menambahkan menggunakan np.newaxis 
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [60]:
#convert 1 D array ke row vector dengan insert ke axis ,1 dimensi
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [61]:
# untuk vektor kolom, Anda dapat menyisipkan axis di sepanjang dimensi kedua

col_vector = a[:, np.newaxis]
col_vector.shape
print(col_vector)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [62]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [63]:
# You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [64]:
# You can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
c.shape
print(c)

[[1 2 3 4 5 6]]


##### Indexing and Slicing

In [65]:
data = np.array([1,2,3])
print(data)

[1 2 3]


In [66]:
print(data[0])
print(data[1])

1
2


In [67]:
print(data[0:2])

[1 2]


In [68]:
print(data[1:])

[2 3]


In [69]:
print(data[-2:])

[2 3]


#### mengambil bagian dari array atau elemen tertentu

In [70]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [71]:
# mencetak semua nilai dalam array yang kurang dari 5

print(a[a<5])

[1 2 3 4]


In [72]:
## misalnya, angka yang sama dengan atau lebih besar dari 5, dan menggunakan kondisi tersebut untuk mengindeks array.
five_up = (a >= 5)

print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [73]:
# memilih elemen yang habis dibagi 2
divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [74]:
# memilih elemen yang memenuhi dua kondisi menggunakan & dan | operator

c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


#### Creating Array from Existing Data
    slicing indexing
    np.vstack()
    np.hstack()
    np.hsplit()
    .view()
    .copy(

In [75]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

#### Menumpuk dua array yang ada

In [76]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [77]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [78]:
np.vstack((a_1, a_2)) #Vertical

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [80]:
np.hstack((a_1, a_2)) #Horizon

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

#### Membagi sebuah array menjadi beberapa array yang lebih kecil

In [81]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [82]:
# membagi array ini menjadi tiga array yang sama bentuknya
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

#### membuat objek array baru yang melihat data yang sama dengan array asli

In [84]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [86]:
# membuat objek array baru yang melihat data yang sama

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
# membuat salinan
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### Basic array operations

In [ ]:
data - ones
data * data
data / data

In [88]:
a = np.array([1, 2, 3, 4])

# menambahkan semua elemen dalam array
a.sum()

10

In [89]:
b = np.array([[1, 1], [2, 2]])
print(b)

[[1 1]
 [2 2]]


In [90]:
# Anda dapat menjumlahkan baris
b.sum(axis=0)

array([3, 3])

In [91]:
# Anda dapat menjumlahkan kolom
b.sum(axis=1)

array([2, 4])

In [92]:
data = np.array([1,2])
data

array([1, 2])

In [93]:
ones = np.ones(2)
print(ones)

[1. 1.]


In [94]:
data + ones

array([2., 3.])

In [95]:
data * data 

array([1, 4])

In [96]:
data / data 

array([1., 1.])

#### Broadcasting

    Broadcasting adalah mekanisme yang memungkinkan NumPy untuk melakukan operasi pada array dari berbagai bentuk. 
    Dimensi array Anda harus kompatibel, misalnya, ketika dimensi kedua array sama 
    atau ketika salah satunya adalah 1. Jika dimensi tidak kompatibel, Anda akan mendapatkan kesalahan nilai.

In [98]:
print(data)
print(data * 2) 

[1 2]
[2 4]


#### Function

In [99]:
np.random.seed(0)
print(np.random.randint(10))

5


In [100]:
random_arr = np.random.randint(10,100,6) # dari 10 ke 100 sebanyak 6 
print(random_arr)

[74 77 77 19 93 31]


In [101]:
np.random.seed(0)
random_arr = np.random.randint(3, high=100,
                               size=(2, 2)) ## randint(low, high=None, size=None, dtype=int)

print(repr(random_arr))

array([[47, 50],
       [67, 70]])


In [102]:

# New seed
np.random.seed(2)

random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

array([[43, 18],
       [75, 25]])


In [103]:
# Original seed
np.random.seed(0)
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

array([[47, 50],
       [67, 70]])


#### More Array Operation

Maximum, minimum, sum, mean, product, standard deviation, and more
data.max()
data.min()
data.sum()

In [105]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [106]:
A.sum()

4.8595784

In [107]:
A.min()

0.05093587

In [108]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [109]:
A.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [110]:
A.std()

0.21392120766089617

In [111]:
dataA = A.min(axis=1)
print(dataA)

[0.17296777 0.05093587 0.12697628]


In [112]:
print(dataA.argmin()) ## posisi index

1


In [113]:
print(dataA.argmax()) ## posisi index 

0


#### save array into file 

In [114]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [115]:
np.save("myarray2.npy",A)

In [116]:
responseFile = np.load('myarray2.npy')
print(responseFile)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


## Latihan 

Buat lah Array 
```
[[  0  72   3]
 [  1   3 -60]
 [ -3  -2   4]]
``` 

Simpan file Array tersebut 
Kemudian lakukan load file Array 

lakukan pencarian data dibawah ini 

Temukan Nilai minum dan maksimum pada file tersebut 

Temukan Nilai minum di setiap kolom 
Temukan Nilai Maksimum di setiap Kolom 
Menemukan Nilai Minimum di setiap baris 
Menemukan Nilai Maksimum di setiap baris 

In [118]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(arr)

[[  0  72   3]
 [  1   3 -60]
 [ -3  -2   4]]


In [119]:
np.save("myarray3.npy",arr)


In [120]:
resfile = np.load('myarray3.npy')
print(resfile)

[[  0  72   3]
 [  1   3 -60]
 [ -3  -2   4]]


In [121]:
print(resfile.min())
print(resfile.max())

print(repr(resfile.min(axis=0)))
print(repr(resfile.max(axis=0)))

print(repr(resfile.max(axis=-1)))
print(repr(resfile.min(axis=-1)))

-60
72
array([ -3,  -2, -60])
array([ 1, 72,  4])
array([72,  3,  4])
array([  0, -60,  -3])


#### Matrices

Membuat Matriks

In [123]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.27265629, 0.47766512],
       [0.81216873, 0.47997717],
       [0.3927848 , 0.83607876]])

In [122]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.85794562 0.84725174]
 [0.6235637  0.38438171]
 [0.29753461 0.05671298]]


#### Matrix Arithmetic

dapat menjumlahkan dan mengalikan matriks menggunakan operator aritmatika (+ - * / ) 
Jika kedua matriks tersebut berukuran sama. 
Numpy menangani sebagai position-wise operations. 

In [125]:
data = np.array([[1,2],[3,4]])
print(data)

[[1 2]
 [3 4]]


In [126]:
ones = np.ones([2,2]) 
print(ones)

[[1. 1.]
 [1. 1.]]


In [127]:
print(data+ones)

[[2. 3.]
 [4. 5.]]


In [128]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [129]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


In [130]:
data1 = np.array([[1,2],[3,4],[5,6]])
print(data1)

[[1 2]
 [3 4]
 [5 6]]


In [131]:
print(data1 + ones_row)

[[2. 3.]
 [4. 5.]
 [6. 7.]]


In [132]:
data2 = np.array([[1,2,3],[4,5,6]])
print(data2)

[[1 2 3]
 [4 5 6]]


#### Dot Product 
    
    Perbedaan utama yang harus dibuat dengan aritmatika adalah kasus perkalian matriks menggunakan produk titik. NumPy memberikan setiap matriks metode dot() yang dapat kita gunakan untuk melakukan operasi p

In [133]:
np.dot(3, 4)

12

In [134]:
a = np.arange(3*4*5*6).reshape((3,4,5,6)) 
print(a)

[[[[  0   1   2   3   4   5]
   [  6   7   8   9  10  11]
   [ 12  13  14  15  16  17]
   [ 18  19  20  21  22  23]
   [ 24  25  26  27  28  29]]

  [[ 30  31  32  33  34  35]
   [ 36  37  38  39  40  41]
   [ 42  43  44  45  46  47]
   [ 48  49  50  51  52  53]
   [ 54  55  56  57  58  59]]

  [[ 60  61  62  63  64  65]
   [ 66  67  68  69  70  71]
   [ 72  73  74  75  76  77]
   [ 78  79  80  81  82  83]
   [ 84  85  86  87  88  89]]

  [[ 90  91  92  93  94  95]
   [ 96  97  98  99 100 101]
   [102 103 104 105 106 107]
   [108 109 110 111 112 113]
   [114 115 116 117 118 119]]]


 [[[120 121 122 123 124 125]
   [126 127 128 129 130 131]
   [132 133 134 135 136 137]
   [138 139 140 141 142 143]
   [144 145 146 147 148 149]]

  [[150 151 152 153 154 155]
   [156 157 158 159 160 161]
   [162 163 164 165 166 167]
   [168 169 170 171 172 173]
   [174 175 176 177 178 179]]

  [[180 181 182 183 184 185]
   [186 187 188 189 190 191]
   [192 193 194 195 196 197]
   [198 199 200 201 202 203]


In [135]:
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
print(b)

[[[[359 358 357]
   [356 355 354]
   [353 352 351]
   [350 349 348]
   [347 346 345]
   [344 343 342]]

  [[341 340 339]
   [338 337 336]
   [335 334 333]
   [332 331 330]
   [329 328 327]
   [326 325 324]]

  [[323 322 321]
   [320 319 318]
   [317 316 315]
   [314 313 312]
   [311 310 309]
   [308 307 306]]

  [[305 304 303]
   [302 301 300]
   [299 298 297]
   [296 295 294]
   [293 292 291]
   [290 289 288]]]


 [[[287 286 285]
   [284 283 282]
   [281 280 279]
   [278 277 276]
   [275 274 273]
   [272 271 270]]

  [[269 268 267]
   [266 265 264]
   [263 262 261]
   [260 259 258]
   [257 256 255]
   [254 253 252]]

  [[251 250 249]
   [248 247 246]
   [245 244 243]
   [242 241 240]
   [239 238 237]
   [236 235 234]]

  [[233 232 231]
   [230 229 228]
   [227 226 225]
   [224 223 222]
   [221 220 219]
   [218 217 216]]]


 [[[215 214 213]
   [212 211 210]
   [209 208 207]
   [206 205 204]
   [203 202 201]
   [200 199 198]]

  [[197 196 195]
   [194 193 192]
   [191 190 189]
   [188 1

In [136]:
np.dot(a, b)[2,3,2,1,2,2]

499128

In [137]:
sum(a[2,3,2,:] * b[1,2,:,2])

499128

### Matrix Indexing
    Operasi pengindeksan dan pemotongan menjadi lebih berguna saat kita memanipulasi matriks
    
    
   ```np.array([[1, 2], [3, 4], [5, 6]])```

    
<img src="https://i.ibb.co/4sS8HGD/Screen-Shot-2021-09-02-at-8-26-34-AM.png" align="left"> 


In [140]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)

[[1 2]
 [3 4]
 [5 6]]


In [141]:
print(data[0,1])

2


In [142]:
print(data[1:3])

[[3 4]
 [5 6]]


In [144]:
print((data[0:2, 0]))

[1 3]


In [143]:
print((data[:]))

[[1 2]
 [3 4]
 [5 6]]


In [145]:
print(data[:, -1]) # -1 kanan
xdata = data[:, -1]
xdata.ndim  # 1 dimensi
##xdata.shape

[2 4 6]


1

In [146]:
print(data[:, 1:]) # -1 kanan
xdata = data[:, 1:]
xdata.ndim  # 2 dimensi
#xdata.shape

[[2]
 [4]
 [6]]


2

In [147]:
print(data[:, :]) 

[[1 2]
 [3 4]
 [5 6]]


In [148]:
print(data[:, 0:1]) 

[[1]
 [3]
 [5]]


In [149]:
print(data[:, 1:2]) 

[[2]
 [4]
 [6]]


In [150]:
print(data[:, 1:]) 

[[2]
 [4]
 [6]]


In [151]:
print((data[0:2,:]))

[[1 2]
 [3 4]]


In [152]:
print(repr(data[0:1, 1:]))

array([[2]])


# Latihan Studi Kasus

10nbuah botol minum akan dibuat untuk menyimpan air dengan jari2 yang berbeda-beda. Besaran jari2 dan tinggi botol adalah bilangan bulat kisaran 7 sampai dengan 20 cm. 

Tentukan
1. Volume air yang dapat disimpan di setiap botol
2. Total volume air yang tersimpan dalam semua botol
3. Botol mana yang volume air terkecil dan temukan volumenya
4. Botol mana yang menampung volume air terbesar dan temukan volume airnya
5. Rata-rata volume yang dapat ditampung di tiap botol

In [154]:
import numpy as np
np.random.seed(0)
dataBotol = np.random.randint(7,20,20)
print(dataBotol)

[19 12  7 10 18 10 14 16 10 12  9 11 14 13 15 15 19 17  8 13]


In [155]:
dataBotol.resize(10,2)
print(dataBotol)

[[19 12]
 [ 7 10]
 [18 10]
 [14 16]
 [10 12]
 [ 9 11]
 [14 13]
 [15 15]
 [19 17]
 [ 8 13]]


In [156]:
## Tinggi kolom = 0
## jari kolom = 1
volume = np.pi * dataBotol[:,1]**2 * dataBotol[:,0]
print(volume)

[ 8595.39750022  2199.11485751  5654.86677646 11259.46807047
  4523.89342117  3421.19439976  7433.00821839 10602.87520587
 17250.48526086  4247.43326765]


In [157]:
volume.sum()

75187.73697836453

In [158]:
volume.argmin()
volume[volume.argmin()]

2199.1148575128555

In [159]:
volume.argmax()
volume[volume.argmax()]

17250.485260861555

In [160]:
idxBotolKecil = volume.argmin()
volumeBotolKecil = volume[idxBotolKecil]
print(f"Botol Terkecil Pada Botol index : {idxBotolKecil} volume {volumeBotolKecil}")
idxBotolBesar = volume.argmax()
volumeBotolBesar = volume[idxBotolBesar]
print(f"Botol Terkecil Pada Botol index : {idxBotolBesar} volume {volumeBotolBesar}")


Botol Terkecil Pada Botol index : 1 volume 2199.1148575128555
Botol Terkecil Pada Botol index : 8 volume 17250.485260861555


## latihan index

In [161]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print((arr[:]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [162]:
print((arr[1:]))

[[4 5 6]
 [7 8 9]]


In [163]:
print(repr(arr[:, -1]))

array([3, 6, 9])


In [164]:
print(repr(arr[:, 1:]))

array([[2, 3],
       [5, 6],
       [8, 9]])


In [165]:
print(repr(arr[0:1,:]))

array([[1, 2, 3]])


In [168]:
print(repr(arr[0:2,:]))

array([[1, 2, 3],
       [4, 5, 6]])


In [166]:
print(repr(arr[0:1, 1:]))

array([[2, 3]])


In [167]:
print(repr(arr[0:2, 1:]))

array([[2, 3],
       [5, 6]])


In [169]:
print(repr(arr[0, 1:]))

array([2, 3])


### Matrix Aggregation
    Kita dapat menjumlahkan matriks dengan cara yang sama seperti kita menjumlahkan vector

In [170]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)

[[1 2]
 [3 4]
 [5 6]]


In [171]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [172]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


## Transposing and Reshaping

mentraspose suatu array adalah proses mengubah posisi **element2 vektor baris menjadi vektor kolom demikian pula sebaliknya.* 

Menggunakan numpy , melakukan traspose suatu array dapat dilakukan : 
 dengan cara memangil function **transpose()** atau memanggil properti **T** dari suatu array  

In [173]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [174]:
print(data.transpose())

[[1 3 5]
 [2 4 6]]


In [175]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [176]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)
data = data.transpose()
print(data)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


Metode reshape() NumPy berguna dalam kasus ini. 
    Anda hanya memberikan dimensi baru yang Anda inginkan untuk matriks. 
    Anda dapat meneruskan -1 untuk suatu dimensi dan NumPy dapat menyimpulkan dimensi yang benar berdasarkan matriks Anda

In [177]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [178]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [179]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [180]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


### N-Dimensional Array 
    NumPy dapat melakukan semua yang telah kita sebutkan dalam sejumlah dimensi. Struktur data pusatnya disebut ndarray (N-Dimensional Array) karena suatu alasan.

In [181]:
import numpy as np 

In [182]:
ndarr = np.array([ [[1,2],[3,4]],
                  [[5,6],[7,8]] ])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [183]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [184]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [185]:
print(np.random.random((4,3,2)))

[[[0.81216873 0.47997717]
  [0.3927848  0.83607876]
  [0.33739616 0.64817187]]

 [[0.36824154 0.95715516]
  [0.14035078 0.87008726]
  [0.47360805 0.80091075]]

 [[0.52047748 0.67887953]
  [0.72063265 0.58201979]
  [0.53737323 0.75861562]]

 [[0.10590761 0.47360042]
  [0.18633234 0.73691818]
  [0.21655035 0.13521817]]]


### Flatten N-Dimensional Array

Ada dua cara populer untuk meratakan array: .flatten() dan .ravel(). Perbedaan utama antara keduanya adalah bahwa array baru yang dibuat menggunakan ravel() sebenarnya adalah referensi ke array induk. Ini berarti bahwa setiap perubahan pada array baru akan mempengaruhi array induk juga. Karena ravel tidak membuat salinan, ini hemat memori.

In [186]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [187]:
# You can use flatten to flatten your array into a 1D array.
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])